site_name: WebGPU Native
site_url: https://webgpu-native.github.io/webgpu-headers
docs_dir: src
nav:
  - Home: index.md
  - Overview: overview.md
  - API: api.md
markdown_extensions:
  - attr_list
  - toc:
      permalink: "#"
